const countries = {
    "ar-SA": "Arabic",
    "bn-IN": "Bengali",
    "ca-ES": "Catalan",
    "de-DE": "German",
    "en-US": "English (US)",
    "en-GB": "English (UK)",
    "fr-FR": "French",
    "hi-IN": "Hindi",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "kn-IN": "Kannada",
    "ko-KR": "Korean",
    "ne-NP": "Nepali",
    "ur-PK": "Urdu",
    "pa-IN": "Punjabi",
    "ru-RU": "Russian",
    "si-LK": "Sinhala",
    "ta-IN": "Tamil",
    "te-IN": "Telugu",
};